version: '3.7'
services:

  proxy:
    build:
      context: .
      args:
        link: 'iris'
        port: '52773'
    image: proxyiris:latest
    ports:
    - "80:80"
    - "443:443"

  iris:
    image: store/intersystems/iris:2019.1.0.510.0-community
    hostname: iris
    ports:
    - "51776:51773" # 51773 is the superserver default port
    - "52776:52773" # 52773 is the webserver/management portal port
